#!/usr/bin/env python
import sys, os, ConfigParser, time
import putio


########################################################################
# Utility functions
########################################################################

lst_folder2id = dict()
lst_id2folder = dict()
dl_creds = {}

#-------------------
# get_all_children
#-------------------

def get_all_children(api, parent):
  if (parent is None):
    parent_id = 0
  else:
    parent_id = parent.id

  fetch_at_once = 50
  subitems = []
  offset = 0
  try:
    items = api.get_items(parent_id=parent_id, limit=fetch_at_once, offset=0)
    subitems.extend(items)
    while len(items) == fetch_at_once:
      try:
        items = api.get_items(parent_id=parent_id, limit=fetch_at_once, offset=offset)
        offset = offset + fetch_at_once
        subitems.extend(items)
      except putio.PutioError:
        pass
  except putio.PutioError:
    pass

  subitems.sort(lambda x,y: (-1 if x.is_dir else 1) if x.is_dir != y.is_dir else cmp(x.name, y.name))
  return subitems

#---------------------
# update_cached_tree
#---------------------

def update_cached_tree(api, force=False):
  if len(lst_id2folder) and not force:
    return

  def add_subitems(path, parent, subitems):
    if (parent is None):
      path='/'
      parent_id=0
    else:
      path=path+parent.name+'/'
      parent_id=parent.id

    added = 0
    for f in subitems:
      added = added + 1
      name = path+f.name
      #try:
      #  print name
      #except:
      #  print path+'[Unprintable]'
      lst_folder2id[name] = f.id
      lst_id2folder[f.id] = f
      subitems = get_all_children(api, f)
      added = added + add_subitems(path, f, subitems)

    return added

  subitems = get_all_children(api, f)
  add_subitems('', None, subitems)

#----------------
# strip_slashes
#----------------

def strip_slashes(path):
  return '/'.join([segment for segment in path.split('/') if segment != ''])

#--------------------
# resolve_path_walk
#--------------------

def resolve_path_walk(api, path, parent):
  # strip leading and trailing slashes
  path = strip_slashes(path)
  # break into head/tail
  (this_segment, ignore, rest) = path.partition('/')
  if this_segment == '':
    return parent
  subitems = get_all_children(api, parent)
  for subitem in subitems:
    if subitem.name == this_segment:
      return resolve_path_walk(api, rest, subitem)

  raise NameError('Path element "%s" not found in "%s"' % (this_segment, parent.name if parent is not None else '/'))

#---------------
# resolve_path
#---------------

def resolve_path(api, path, preprocess = False):
  """Resolve a path to a file/directory object, or throw a NameError if not found. Returns None for the root directory."""
  if (preprocess):
    update_cached_tree(api)
  if len(lst_id2folder):
    return lst_id2folder[lst_folder2id[path]]
  return resolve_path_walk(api, path, None)

#-----------------
# fetch_via_curl
#-----------------

def fetch_via_curl(url, target, item_name):
  import pycurl

  c = pycurl.Curl()
  url = str(url)
  c.setopt(pycurl.URL, url)

  #file_id = open(target, 'wb')
  # no resume support in put.io yet :-(
  if os.path.exists(target):
    file_id = open(target, 'ab')
    c.setopt(pycurl.RESUME_FROM, os.path.getsize(target))
  else:
    file_id = open(target, 'wb')

  c.setopt(pycurl.USERPWD, dl_creds['user']+':'+dl_creds['password'])
  if dl_creds['limitrate']:
    c.setopt(c.MAX_RECV_SPEED_LARGE, dl_creds['limitrate'])
  c.setopt(pycurl.WRITEDATA, file_id)
  c.setopt(pycurl.NOPROGRESS, 0)
  c.setopt(pycurl.FOLLOWLOCATION, 1)
  c.setopt(pycurl.UNRESTRICTED_AUTH, 1)
  c.setopt(pycurl.SSL_VERIFYPEER, 0)

  def progressHook(total, existing, upload_t, upload_d):
    try:
      frac = float(existing)/float(total)
    except:
      frac = 0.0

    sys.stdout.write("\r%s: %d of %d (%.02f%%)" % (
      item_name,
      existing,
      total,
      frac * 100.0
      ))

  c.setopt(pycurl.PROGRESSFUNCTION, progressHook)
  try:
    c.perform()
    print
  except pycurl.error as e:
    print
    if e[0] == 42:
      print "Aborted download"
      sys.exit(1)
    else:
      try:
        print "Download error %d: %s" % e
      except TypeError:
        print "Download error: %s" % e

#-------------------
# fetch_via_urllib
#-------------------

def fetch_via_urllib(url, target, item_name):
  import urllib

  class AuthedUrlOpener(urllib.FancyUrlOpener):
    def prompt_user_passwd(host, realm):
      return (dl_creds['user'], dl_creds['password'])
  urllib._urlopener = AuthedUrlOpener()

  download_started_at = 0.0
  def progressHook(block_count, block_size, total_size):
    global download_started_at
    if (block_count == 0):
      download_started_at = time.time()

    sys.stdout.write("\r%s: %d of %d (%.02f%%) at %.02fKiB/s" % (
      item_name,
      block_count*block_size,
      total_size,
      100*float(float(block_count*block_size) / float(total_size)),
      float(float(float(block_count*block_size)/1024) / float(time.time()-download_started_at))
      ))

  urllib.urlretrieve(url, target, progressHook)


#--------
# fetch
#--------

def fetch(url, target, item_name):
  return fetch_via_curl(url, target, item_name)
  #return fetch_via_urllib(url, target, item_name)


########################################################################
# Commands
########################################################################

#-------
# info
#-------

def info(api, args=[]):
  """Display user information about available bandwidth and disk space"""
  me = api.get_user_info()

  print "Available bandwidth : %s/%s" % (putio.human_size(me.bw_quota_available), putio.human_size(me.bw_quota))
  print "Available disk space: %s/%s" % (putio.human_size(me.disk_quota_available), putio.human_size(me.disk_quota))

#-----
# ls
#-----

def ls(api, args):
  """List directory contents"""
  def ls_format(item, maxlen=0):
    maxlen = (str(maxlen) if maxlen != 0 else '')
    if item.is_dir:
      return ("drwxrwxrwx  %"+maxlen+"s %s/") % ('', item.name)
    else:
      return ("-rwxrwxrwx  %"+maxlen+"s %s") % (item.size, item.name)

  if (len(args) == 0):
    item = None
  elif (len(args) == 1):
    item = resolve_path(api, args[0])
  else:
    print "Expected: at most one argument"
    return

  if item is None or item.is_dir:
    subitems = get_all_children(api, item)
    if len(subitems):
      maxlen = reduce(lambda x,y: max(x,y), map(lambda x: 0 if x.is_dir else len(x.size), subitems))
      for i in subitems:
        print ls_format(i, maxlen)
    else:
      print "[No items]"
  else:
    print ls_format(item)

#-----
# rm
#-----

def rm(api, args):
  """Remove a file/folder"""

  if (len(args) == 0):
    item = None
  elif (len(args) == 1):
    item = resolve_path(api, args[0])
  else:
    print "Expected: at most one argument"
    return

  if item is None:
    print "Cannot delete the root element"
    return

  item.delete_item()

#-----
# mv
#-----

def mv(api, args):
  """Rename a file/folder"""
  pass

#--------
# mkdir
#--------

def mkdir(api, args):
  """Create a folder"""

  if (len(args) != 1):
    print "Expected one argument: directory to create"
    return

  # strip leading and trailing slashes
  path = strip_slashes(args[0])
  (path, ignore, last_seg) = path.rpartition('/')

  item = resolve_path(api, '/'+path)

  if item is None:
    api.create_folder(name=last_seg)
  elif item.is_dir:
    item.create_folder(name=last_seg)
  else:
    print "Cannot make a directory under a file!"

#------
# add
#------

def add(api, args):
  """Add one or more URLs for download"""
  if (len(args) == 0):
    text = ''.join(sys.stdin.readlines())
  else:
    text = "\n".join(args)

  bucket = api.create_bucket()
  urls = bucket.extract_urls(text)
  #print urls
  if len(urls) > 0:
    report = bucket.analyze(urls)
    print "\n------------------------------------------------------------------------"
    print "Required space         :", putio.human_size(report['Required Space'])
    print "Current space available:", putio.human_size(report['Current Available Disk Space'])
    print "URLs:"
    for url in report['Urls']['multiparturl']:
      print "  [m] %s" % url
    for url in report['Urls']['singleurl']:
      if url.error is not None:
        print "  [u] %s (%s) ERROR: %s" % (url.url, putio.human_size(url.size), url.error)
      else:
        print "  [u] %s (%s)" % (url.url, putio.human_size(url.size))
    for torrent in report['Urls']['torrenturl']:
      if torrent.error is not None:
        print "  [t] %s (%s) ERROR: %s" % (torrent.name, putio.human_size(torrent.size), torrent.error)
      else:
        print "  [t] %s (%s)" % (torrent.name, putio.human_size(torrent.size))
    for error in report['Urls']['error']:
      print "  [!] %s" % error
    bucket.fetch()
  else:
    print "No URLs found"

#---------
# geturl
#---------

def geturl(api, args):
  """Return the download URL for the given path"""
  if (len(args) != 1):
    print "Expected one argument: path to retrieve URL for"
    return

  item = resolve_path(api, args[0])
  if item is None or item.is_dir:
    print "Directories have no URL"
  else:
    print item.get_download_url()

#----------------
# get_recursive
#----------------

def get_recursive(api, root):
  """Download all files from the "root" directory."""
  if (len(dl_creds) == 0):
    print "Please make sure your download credentials are set in %s" % os.path.expanduser('~/.config/putio-cli/config')
    return

  target = os.path.join(os.getcwd(), root.name) if root is not None else os.getcwd()

  if root is None or root.is_dir:
    if root is not None:
      try:
        os.makedirs(target)
      except OSError:
        pass
      os.chdir(target)

    subitems = get_all_children(api, root)
    for item in subitems:
      get_recursive(api, item)
    os.chdir(os.path.dirname(target))

  else:
    url = root.get_download_url()
    print "Downloading %s into %s" % (root.name, os.getcwd())

    fetch(url, target, root.name)

#------
# get
#------

def get(api, args):
  """Download the given file to the current directory."""
  if (len(dl_creds) == 0):
    print "Please make sure your download credentials are set in %s" % os.path.expanduser('~/.config/putio-cli/config')
    return

  if (len(args) == 0):
    print "Expected arguments: path(s) to retrieve"
    return

  for path in args:
    item = resolve_path(api, path)
    if item is None or item.is_dir:
      get_recursive(api, item)
      return

    target = os.path.join(os.getcwd(), item.name)
    url = item.get_download_url()
    print "Downloading %s from %s" % (item.name, url)

    fetch(url, target, item.name)

#-------------------
# dispatch_command
#-------------------

def dispatch_command(api, cmd, args=[]):
  """Run the appropriate function for a given command"""
  if (cmd == 'info'):
    info(api, args)
  elif (cmd == 'add'):
    add(api, args)
  elif (cmd == 'ls'):
    ls(api, args)
  elif (cmd == 'get'):
    get(api, args)
  elif (cmd == 'geturl'):
    geturl(api, args)
  elif (cmd == 'mkdir'):
    mkdir(api, args)
  elif (cmd == 'rm'):
    rm(api, args)
  else:
    print "Unrecognised command: %s" % cmd

########################################################################
# Main entry point
########################################################################

if __name__ == '__main__':
  try:
    config = ConfigParser.ConfigParser()
    config.read([os.path.expanduser('~/.config/putio-cli/config')])
    try:
      api = putio.Api(api_key=config.get('api', 'key'), api_secret=config.get('api', 'secret'))
    except (ConfigParser.NoSectionError, ConfigParser.NoOptionError):
      print "Please make sure your API credentials are set in %s" % os.path.expanduser('~/.config/putio-cli/config')
      sys.exit(1)
    except Exception as e:
      print 'An error occurred while connecting to put.io: %s' % e
      sys.exit(1)

    # try to retrieve download credentials
    try:
      dl_creds['user'] = config.get('download', 'user')
      dl_creds['password'] = config.get('download', 'password')
      dl_creds['limitrate'] = config.getint('download','limitrate')
    except (ConfigParser.NoSectionError, ConfigParser.NoOptionError):
      dl_creds = {}

    if not api.is_ready():
      print "Please make sure your API credentials are correct in %s" % os.path.expanduser('~/.config/putio-cli/config')
      sys.exit(1)

    if len(sys.argv) > 2:
      dispatch_command(api, sys.argv[1], sys.argv[2:])
    elif len(sys.argv) > 1:
      dispatch_command(api, sys.argv[1])
    else:
      info(api)
  except KeyboardInterrupt as e:
    sys.exit(2)
